### PR TITLE
Issue #222 - YAML support 

### PR DESCRIPTION
**Pull request by jackfreeman88**
1. Compare experiments with visualize.py 
2. YAML file path assignment

### CODE REVIEW

**Comment by andrewprzh** [comment]
Am I right that we actually need only this commit?
https://github.com/ablab/IsoQuant/pull/224/commits/8ffa4a8cb9cf8c903d01798890f5097468ded24c

**Comment by andrewprzh** [comment]
[This commit](https://github.com/ablab/IsoQuant/pull/224/commits/098ad38ae4c49538f1a5e6aa9a18aa67aa0063c0) contains main file reformating, I would prefer not to modify it while there are a few dev branches

**Comment by jackfreeman88** [comment]
Ahh yes my my formatter, I shouldn't have even included the isoquant file in my commit!

**Comment by andrewprzh** [comment]
Thanks @jackfreeman88
Closing now in favor of cherry-picked commit

**Pull request closed without merging**
